[features]
seeds = false
skip-lint = false

[programs.localnet]
alphastake = "FQCkNt3RvwbWLyqLocbWSwWiTZqkb4dqDHBSTd3v8JLq"

[programs.devnet]
alphastake = "FQCkNt3RvwbWLyqLocbWSwWiTZqkb4dqDHBSTd3v8JLq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
